### ISSUE TITLE
Download the generated glitched image as .gif animation

### ISSUE THREAD

**Issue by IceM4nn** [akx/glitch2#1]
Hello, how to download the generated glitched image as .gif? as I click "save current image" it download the current image .png. I want the .gif format with all the animation that I just set up.

Here is my state export:
```
{"defs":[{"id":"-nvm3y3","moduleName":"streak","options":{"xOffsetChance":15,"yOffsetChance":15,"offsetHalveChance":500,"offsetResetEveryLine":false},"enabled":true,"probability":0.05},{"id":"tay1ag","moduleName":"sliceglitch","options":{"chanR":true,"chanG":true,"chanB":true,"randomChan":true,"blend":0.8,"driftProb":0,"driftMag":1,"heightMin":0.02,"heightMax":0.02,"nMin":0,"nMax":20,"offsetMin":-15,"offsetMax":15},"enabled":true,"probability":0.34}]}
```
Hope that you can help.

**Comment by akx** [comment]
Hi @HazmirulZ,

Currently it's not possible to download an animation directly, unfortunately. (It would require encoding a GIF in the browser, which while not impossible, takes some more work.)

However you can save a sequence of images using "save current image", then use something like http://gifmaker.me/ (I just [googled for 'png sequence to gif' -- there are other tools](https://www.google.com/search?q=png+sequence+to+gif)) to reconstitute a gif out of those PNGs.

Hope that helps, and thanks for your interest in the tool :)

**Comment by akx** [comment]
By the way, GIF encoding is now available :)
