### ISSUE TITLE
Paste images into Glitch2

### ISSUE THREAD

**Issue by ornithologistnightmare** [akx/glitch2#2]
If you're still working on this, please add an 'upload via clipboard' feature. There's plenty of tutorials [here](https://eu.startpage.com/do/asearch) but I can't understand them enough to do it myself even after a few hours of trying.

**Comment by akx** [comment]
Oh, hey, good idea.
Shouldn't be too hard to implement. :)

**Comment by akx** [comment]
@ReceivedChunky The version now up on http://akx.github.io/glitch2/ has paste and resize! 🎉

**Comment by ornithologistnightmare** [comment]
Thanks, that's perfect with a cherry on top! It'll make creating things like this a lot easier:

![image](https://cloud.githubusercontent.com/assets/7671948/26828505/a2990f9a-4ab9-11e7-990d-ee91e4269e7b.png)
